src/br/com/aviva/controle/ListaContratoBean.java
package br.com.aviva.controle;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.persistence.EntityManager;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import br.com.aviva.modelo.entidades.Contrato;
import br.com.aviva.modelo.repositorio.ContratoRepository;
import br.com.aviva.services.CepWebService;

@ManagedBean
public class ListaContratoBean implements Serializable {

	private Contrato contrato = new Contrato();
	private List<Contrato> contratos ;
		
	public void confirmacaoBoleto () throws IOException {
		
		Map <String,String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
		Long id = Long.parseLong (params.get("id"));
		EntityManager manager = this.getManager();
		ContratoRepository repository = new ContratoRepository(manager);
		this.contrato = repository.procura(id);
		
		if (this.contrato.getFlag_boleto_emitido() == true) {
			this.contrato.setFlag_boleto_emitido(false);
		} else {
			this.contrato.setFlag_boleto_emitido(true);
		}
		
		if (this.contrato.getId() == null) {			
			repository.adiciona(this.contrato);			
		} else {			
			repository.atualiza (this.contrato);			
		}
		
		FacesContext fc = FacesContext.getCurrentInstance();
		ExternalContext ec = fc.getExternalContext();
		
		if (this.contrato.getUnidade().equals("Boninas")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_boninas.xhtml");
		}
		
		if (this.contrato.getUnidade().equals("Moema")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_moema.xhtml");
		}
		
		if (this.contrato.getUnidade().equals("Brooklin")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_brooklin.xhtml");
		}
		
		
	}
	
	public void preparaAprovacao () throws IOException {
		
		Map <String,String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
		Long id = Long.parseLong (params.get("id"));
		EntityManager manager = this.getManager();
		ContratoRepository repository = new ContratoRepository(manager);
		this.contrato = repository.procura(id);
		
		this.contrato.setStatus_contrato("A");
		this.contrato.setFlag_periodo_alterado(false);
		this.contrato.setTexto_periodo_alterado("");
		
		if (this.contrato.getId() == null) {			
			repository.adiciona(this.contrato);			
		} else {			
			repository.atualiza (this.contrato);			
		}
		
		FacesContext fc = FacesContext.getCurrentInstance();
		ExternalContext ec = fc.getExternalContext();
		
		if (this.contrato.getUnidade().equals("Boninas")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_boninas.xhtml");
		}
		
		if (this.contrato.getUnidade().equals("Moema")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_moema.xhtml");
		}
		
		if (this.contrato.getUnidade().equals("Brooklin")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_brooklin.xhtml");
		}
			
	}
	
	public void preparaAprovacaoHorario () throws IOException {
		
		Map <String,String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
		Long id = Long.parseLong (params.get("id"));
		EntityManager manager = this.getManager();
		ContratoRepository repository = new ContratoRepository(manager);
		this.contrato = repository.procura(id);
		
		this.contrato.setStatus_contrato("L");
		this.contrato.setFlag_periodo_alterado(false);
		this.contrato.setTexto_periodo_alterado("");
		
		if (this.contrato.getId() == null) {			
			repository.adiciona(this.contrato);			
		} else {			
			repository.atualiza (this.contrato);			
		}
		
		FacesContext fc = FacesContext.getCurrentInstance();
		ExternalContext ec = fc.getExternalContext();
		
		if (this.contrato.getUnidade().equals("Boninas")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_boninas.xhtml");
		}
		
		if (this.contrato.getUnidade().equals("Moema")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_moema.xhtml");
		}
		
		if (this.contrato.getUnidade().equals("Brooklin")) {
			ec.redirect(ec.getRequestContextPath() + "/lista_contratos_brooklin.xhtml");
		}
	}

	public void preparaAlteracao () throws IOException {
		Map <String,String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
		Long id = Long.parseLong (params.get("id"));
		EntityManager manager = this.getManager();
		ContratoRepository repository = new ContratoRepository(manager);
		this.contrato = repository.procura(id);
		System.out.println("==========================================================");
		System.out.println("Contrato encontrado: " + this.contrato.getId());
		FacesContext fc = FacesContext.getCurrentInstance();
		ExternalContext ec = fc.getExternalContext();
		ec.redirect(ec.getRequestContextPath() + "/contrato.xhtml");
	}
	
	public void preparaImpressao () throws IOException {
		Map <String,String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
		Long id = Long.parseLong (params.get("id"));
		EntityManager manager = this.getManager();
		ContratoRepository repository = new ContratoRepository(manager);
		this.contrato = repository.procura(id);
		System.out.println("==========================================================");
		System.out.println("Contrato encontrado: " + this.contrato.getId());
		if (this.contrato.getFlag_concordo_contrato()) {
			FacesContext fc = FacesContext.getCurrentInstance();
			ExternalContext ec = fc.getExternalContext();
			ec.redirect(ec.getRequestContextPath() + "/contrato_impressao.xhtml");
		} else {
			FacesContext fc = FacesContext.getCurrentInstance();
			ExternalContext ec = fc.getExternalContext();
			ec.redirect(ec.getRequestContextPath() + "/contrato_nao_impressao.xhtml");
		}
		
	}
	
	public List <Contrato> getContratos() {		
			if (this.contratos == null) {
				EntityManager manager = this.getManager();
				ContratoRepository repository = new ContratoRepository(manager);
				this.contratos = repository.getLista();
			}
			return this.contratos ;		
	}
	
	public List <Contrato> getContratosBoninas() {		
		if (this.contratos == null) {
			EntityManager manager = this.getManager();
			ContratoRepository repository = new ContratoRepository(manager);
			this.contratos = repository.getListaUnidade("Boninas");
		}
		return this.contratos ;		
	}
	
	public List <Contrato> getContratosMoema() {		
		if (this.contratos == null) {
			EntityManager manager = this.getManager();
			ContratoRepository repository = new ContratoRepository(manager);
			this.contratos = repository.getListaUnidade("Moema");
		}
		return this.contratos ;		
	}
	
	public List <Contrato> getContratosBrooklin() {		
		if (this.contratos == null) {
			EntityManager manager = this.getManager();
			ContratoRepository repository = new ContratoRepository(manager);
			this.contratos = repository.getListaUnidade("Brooklin");
		}
		return this.contratos ;		
	}
	
	public List<Object> getContratosVisualizados() {		
		
		List<Object> retorno = new ArrayList();
		EntityManager manager = this.getManager();
		ContratoRepository repository = new ContratoRepository(manager);
		retorno = repository.getListaContratosVisualizados();
		
		//Varre o objeto retornado do SQL
		Iterator<Object> ite =retorno.iterator();
		
		System.out.println("Passou aqui...");
		while (ite.hasNext()) {
            Object[] result = (Object[]) ite.next();
            long total = (long) result[0];
            String unidade = (String) result[1];
            System.out.println("Total: " + total);
            System.out.println("Unidade: " + unidade);
            }
		
		return retorno ;		
	}
	
	
	private EntityManager getManager () {
		FacesContext fc = FacesContext.getCurrentInstance ();
		ExternalContext ec = fc.getExternalContext ();
		HttpServletRequest request = (HttpServletRequest)ec.getRequest ();
		return ( EntityManager ) request . getAttribute ("EntityManager");
	}

	public Contrato getContrato() {
		return contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

		
	
}

WebContent/contrato_emaprovacao.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<ui:composition template="/WEB-INF/templates/template_passo8.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"	
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
	
<ui:define name="conteudo" >
  
<h:form id="form" prependId="false">
<h:inputHidden value="#{contratoBean.contrato.id}" />

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Rematrícula
      </h1>
      <h3>Nome Aluno: #{contratoBean.contrato.nome_aluno}</h3>
      
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="home.xhtml"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item"><a href="#">Rematrícula</a></li>
        <li class="breadcrumb-item active">Confirmação</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="card-title">Solicitação de Alteração de Horário</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        
        <div class="box-body">
            
			<section>
					
			<h1>Sua solicitação de alteração de horário será analisada, pela Aviva e em breve você receberá um retorno.</h1>
			
			<h:graphicImage value="img/image_sucesso.png" width="150px" />
			
			</section>
				
        </div>
        
        
        <!-- /.box-body  -->
        <div class="box-footer">
          <p:messages id="messages" />
          <div class="btn-group">
	         	<p:commandButton value="Ir para Página Principal" ajax="false" type="submit" id="gravar" update="@form" actionListener="#{contratoBean.adiciona_passo8}" styleClass="btn btn-primary" />
	      </div>
        </div>
        <!-- /.box-footer-->
        
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  

</h:form>

</ui:define>
	
</ui:composition>

WebContent/contrato_nao_impressao.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<ui:composition template="/WEB-INF/templates/template_passo8.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"	
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
	
<ui:define name="conteudo" >
  
<h:form id="form" prependId="false">
<h:inputHidden value="#{contratoBean.contrato.id}" />

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Rematrícula
      </h1>
      <h3>Nome Aluno: #{contratoBean.contrato.nome_aluno}</h3>
      
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="home.xhtml"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item"><a href="#">Rematrícula</a></li>
        <li class="breadcrumb-item active">Confirmação</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="card-title">Confirmação</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        
        <div class="box-body">
            
			<section>
					
			<h1>Seu contrato NÃO foi finalizado ainda.</h1>
			
			<h:graphicImage value="img/image_erro.png" width="150px" />
			
			<h4>Favor efetuar as aprovações/validações e finalizar o processo.</h4>
			<h6>Para isso clique no botão Editar na página principal.</h6>
				
						
			</section>
				
        </div>
        
        
        <!-- /.box-body  -->
        <div class="box-footer">
          <div class="btn-group">
              <h:commandLink value="Ir para Página Principal" action="home.xhtml" styleClass="btn btn-primary" />
	      </div>
        </div>
        <!-- /.box-footer-->
        
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  

</h:form>

</ui:define>
	
</ui:composition>

WebContent/home_admin.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<ui:composition template="/WEB-INF/templates/template_admin.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"	
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
	
<ui:define name="conteudo" >
  
<h:form id="form">
	
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Rematrícula
      </h1>
      <h3>Módulo de Gestão</h3>
            
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="home_admin.xhtml"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="breadcrumb-item"><a href="#">Rematrícula</a></li>
        <li class="breadcrumb-item active">Contratos</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">AVIVA</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <h2>Período: 2019</h2>
          <a href="lista_contratos_boninas.xhtml" styleClass="btn btn-warning">Lista de Contratos - Boninas</a>
          <br></br>	
          <a href="lista_contratos_moema.xhtml" styleClass="btn btn-warning">Lista de Contratos - Moema</a>
          <br></br>
          <a href="lista_contratos_brooklin.xhtml" styleClass="btn btn-warning">Lista de Contratos - Brooklin</a>
          
        </div>
        
        <!--<div class="box-body">
	        
	        <div class="row">
				<div class="col-md-4">
		        	<h4>Total de Contratos Visualizados</h4>
			        <h:dataTable id="lista_totais" var="dados" value="#{listaContratoBean.contratosVisualizados}" styleClass="table table-bordered">
				                  	
					    <h:column>
							<f:facet name="header">Unidade</f:facet> 
							<h:outputText value="#{dados[0]}" />
						</h:column>
						<h:column>
							<f:facet name="header">Total</f:facet> 
							<h:outputText value="#{dados[1]}" />
						</h:column>
										
				    </h:dataTable>
	        	</div>  
	        	
	        	<div class="col-md-4">
		        	<h4>Total de Contratos com Solicitação Horário</h4>
			        <h:dataTable id="lista_totais2" var="dados" value="#{listaContratoBean.contratosVisualizados}" styleClass="table table-bordered">
				                  	
					    <h:column>
							<f:facet name="header">Unidade</f:facet> 
							<h:outputText value="#{dados[0]}" />
						</h:column>
						<h:column>
							<f:facet name="header">Total</f:facet> 
							<h:outputText value="#{dados[1]}" />
						</h:column>
										
				    </h:dataTable>
	        	</div>   
	        	
	        	<div class="col-md-4">
		        	<h4>Total de Contratos Aprovados</h4>
			        <h:dataTable id="lista_totais3" var="dados" value="#{listaContratoBean.contratosVisualizados}" styleClass="table table-bordered">
				                  	
					    <h:column>
							<f:facet name="header">Unidade</f:facet> 
							<h:outputText value="#{dados[0]}" />
						</h:column>
						<h:column>
							<f:facet name="header">Total</f:facet> 
							<h:outputText value="#{dados[1]}" />
						</h:column>
										
				    </h:dataTable>
	        	</div>     
	       </div> 
	       
		            
		 </div> -->
        
        <!-- /.box-body -->
        
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  

</h:form>

</ui:define>
	
</ui:composition>

WebContent/lista_contratos_moema.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<ui:composition template="/WEB-INF/templates/template_admin.xhtml"
	xmlns="http://www.w3.org/1999/xhtml " 
	xmlns:h="http://java.sun.com/jsf/html"	
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pl="http://xmlns.jcp.org/jsf/passthrough">
	
<ui:define name="conteudo" >

<h:form id="form">
<h:inputHidden value="#{listaContratoBean.contrato.id}" />
	
	<!-- Content Wrapper. Contains page content -->
    
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Contratos
            <small>Gestão dos contratos</small>
          </h1>
          <ol class="breadcrumb">
	        <li class="breadcrumb-item"><a href="home_admin.xhtml"><i class="fa fa-dashboard"></i> Home</a></li>
	        <li class="breadcrumb-item"><a href="#">Rematrícula</a></li>
	        <li class="breadcrumb-item active">Lista de Contratos</li>
	      </ol>
	      
        </section>

        <!-- Main content -->
        <section class="content">
          
          <!-- Your Page Content Here -->
          <div class="row">
            <!-- left column -->
	            
	          <div class="col-md-12">  <!-- /div rigth column -->
	            <!-- general form elements -->
	              
	            <div class="box box-primary">
	            
	                <div class="box-header with-border">
	                  <h3 class="box-title">Contratos - Unidade Moema</h3>
	                </div><!-- /.box-header -->
	                
	            	<div class="box-body">
	            
	                    <h:dataTable id="lista_clientes" var="dados" value="#{listaContratoBean.contratosMoema}" styleClass="table table-bordered">
		                    	
		                        <h:column>
									<f:facet name="header">Unidade</f:facet> 
									<h:outputText value="#{dados.unidade}" />
								</h:column>
								<h:column>
									<f:facet name="header">Aluno</f:facet> 
									<h:outputText value="#{dados.nome_aluno}" />
								</h:column>
								<h:column>
									<f:facet name="header">Visualizado</f:facet>
									<span class="badge bg-green"><h:outputText rendered="#{dados.flag_primeiro_acesso eq true}" value="SIM" /></span>
									<span class="badge bg-red"><h:outputText rendered="#{dados.flag_primeiro_acesso eq false}" value="NÃO" /></span>
									<span class="badge bg-red"><h:outputText rendered="#{dados.flag_primeiro_acesso == null}" value="NÃO" /></span>
								</h:column>
								<h:column>
									<f:facet name="header">Grupo</f:facet> 
									<h:outputText value="#{dados.grupo}" />
								</h:column>
								<h:column>
									<f:facet name="header">Status</f:facet> 
								  	<span class="badge bg-red"><h:outputText rendered="#{dados.status_contrato eq 'P'}" value="PENDENTE" /></span>
								  	<span class="badge bg-orange"><h:outputText rendered="#{dados.status_contrato eq 'F' and dados.flag_periodo_alterado == null}" value="SOLICITAÇÃO ENVIADA" /></span>
								  	<span class="badge bg-orange"><h:outputText rendered="#{dados.status_contrato eq 'F' and dados.flag_periodo_alterado eq false}" value="SOLICITAÇÃO ENVIADA" /></span>
								  	<span class="badge bg-blue"><h:outputText rendered="#{dados.status_contrato eq 'F' and dados.flag_periodo_alterado eq true}" value="SOLICITAÇAO HORÁRIO" /></span>
								  	<span class="badge bg-yellow"><h:outputText rendered="#{dados.status_contrato eq 'L'}" value="LIBERADO NOVO HORÁRIO" /></span>
								  	<span class="badge bg-green"><h:outputText rendered="#{dados.status_contrato eq 'A'}" value="APROVADO" /></span>
								</h:column>
								<h:column>
									<f:facet name="header">Detalhes</f:facet> 
									<div class="btn-group">
				                      <button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown">
				                        <i class="fa fa-calendar-o"></i>
				                        <span class="caret"></span>
				                        <span class="sr-only">Toggle Dropdown</span>
				                      </button>
				                      <ul class="dropdown-menu" role="menu">
				                         <div class="box-primary">
							                <div class="box-body">
							                  <p class="text-left bg-gray"><strong>Solicitação</strong></p>
											  <p class="text-left">#{dados.texto_periodo_alterado}</p>
											  <hr></hr>
											  <p class="text-left bg-gray"><strong>Contratante</strong></p>
											  <p class="text-left btn-reddit">#{dados.nome_contratante}</p>
											  <p class="text-left btn-reddit">#{dados.celular}</p>
											  
											  <!--<hr></hr>	
											  <p class="text-left bg-gray"><strong>Atividades Extra</strong></p>
											  <p class="text-left btn-reddit">Balé:<span class="badge bg-green"><h:outputText rendered="#{dados.atividade_bale eq true}" value="SIM" /></span><span class="badge bg-red"><h:outputText rendered="#{dados.atividade_bale eq false}" value="NÃO" /></span></p>
											  <p class="text-left"><span class="badge bg-green"><h:outputText rendered="#{dados.atividade_bale_1parcela eq true}" value="1 parcela" /></span></p>
											  <p class="text-left"><span class="badge bg-green"><h:outputText rendered="#{dados.atividade_bale_10parcelas eq true}" value="10 parcelas" /></span></p>
											  <hr></hr>	
											  <p class="text-left btn-reddit">Judô:<span class="badge bg-green"><h:outputText rendered="#{dados.atividade_judo eq true}" value="SIM" /></span><span class="badge bg-red"><h:outputText rendered="#{dados.atividade_judo eq false}" value="NÃO" /></span></p>	
											  <p class="text-left"><span class="badge bg-green"><h:outputText rendered="#{dados.atividade_judo_1parcela eq true}" value="1 parcela" /></span></p>
											  <p class="text-left"><span class="badge bg-green"><h:outputText rendered="#{dados.atividade_judo_10parcelas eq true}" value="10 parcelas" /></span></p>-->										 				  
							                
							                </div><!-- /.box-body -->
							              </div><!-- /.box -->				                        
				         	          </ul>
				                    </div>
								</h:column>
								<h:column headerText="Ação">
								  <f:facet name="header">Editar</f:facet> 
								  <f:ajax event="click" render="@form" listener="#{contratoBean.preparaAlteracao_admin}">
									<h:commandLink>
										<f:param name="id" value="#{dados.id}" />																
										<i class="fa fa-pencil-square-o"></i>
									</h:commandLink>
								  </f:ajax>				  
								</h:column>	
								<h:column headerText="Ação">
								  <f:facet name="header">Resumo</f:facet> 
								  <f:ajax event="click" render="@form" listener="#{contratoBean.preparaAlteracao_resumo}">
									<h:commandLink>
										<f:param name="id" value="#{dados.id}" />																
										<i class="fa fa-pencil-square-o"></i>
									</h:commandLink>
								  </f:ajax>				  
								</h:column>	
								<h:column headerText="Ação">
								  <f:facet name="header">Liberar</f:facet> 
								  <f:ajax event="click" render="@form" listener="#{listaContratoBean.preparaAprovacaoHorario}">
									<h:commandLink rendered="#{dados.flag_periodo_alterado eq true}">
										<f:param name="id" value="#{dados.id}" />																
										<i class="fa fa-check"></i>
									</h:commandLink>
								  </f:ajax>				  
								</h:column>	
								<h:column headerText="Ação">
								  <f:facet name="header">Aprovar</f:facet> 
								  <f:ajax event="click" render="@form" listener="#{listaContratoBean.preparaAprovacao}">
									<h:commandLink rendered="#{dados.status_contrato eq 'F'}">
										<f:param name="id" value="#{dados.id}" />																
										<i class="fa fa-check"></i>
									</h:commandLink>
								  </f:ajax>				  
								</h:column>	
								<h:column headerText="Boleto">
								  <f:facet name="header">Boleto</f:facet> 
								    <span class="badge bg-green"><h:outputText rendered="#{dados.flag_boleto_emitido eq true}" value="SIM"></h:outputText></span>
								  	<span class="badge bg-red"><h:outputText rendered="#{dados.flag_boleto_emitido eq false}" value="NÃO"></h:outputText></span>
								  	<span class="badge bg-red"><h:outputText rendered="#{dados.flag_boleto_emitido == null}" value="NÃO"></h:outputText></span>
								</h:column>
								<h:column headerText="Ação">
								  <f:facet name="header">Imprimir</f:facet> 
								  <f:ajax event="click" render="@form" listener="#{contratoBean.preparaImpressaoQuadroResumo}">
								     <h:commandLink rendered="#{dados.status_contrato eq 'A'}">
									   <f:param name="id" value="#{dados.id}" />
									   <i class="fa fa-print"></i>
									 </h:commandLink>
								  </f:ajax> 								  
								</h:column>
		                  </h:dataTable>
		            
		                  
                	</div><!-- /.box-body -->
                
              	</div><!-- /.box -->    
                
	          </div>  <!-- /.div rigth column -->
	          
           </div> <!-- /.div row -->
          
        </section><!-- /.content -->
        
      </div><!-- /.content-wrapper -->
		
</h:form>

</ui:define>
	
</ui:composition>